'use client';
import { FormEvent, useState } from 'react';
import type { Plan } from '../lib/plan';
const today = new Date().toISOString().slice(0, 10);
const sourceName = (state: string) => state === 'live' ? '实时查询' : state === 'demo' ? '演示数据' : '待接入';
export default function Home() {
  const [plan, setPlan] = useState<Plan | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch('/api/plan', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(values) }); const json = await response.json(); if (!response.ok) throw Error(json.error); setPlan(json); } catch (e) { setError(e instanceof Error ? e.message : '生成失败'); } finally { setLoading(false); } }
  return <main><header><div className="brand">TRAVELCANVAS <span>中国旅行规划</span></div><p>路线以数据校验，灵感由 AI 生成</p></header><section className="hero"><div><span className="eyebrow">可信旅行方案 · BETA</span><h1>让每一步，<em>更值得抵达。</em></h1><p>从目的地、预算和偏好出发，获得可调整的每日路线、天气提醒与住宿建议。</p></div><aside><b>本期能力</b><span>✓ 中国境内目的地</span><span>✓ 路线优先排序</span><span>✓ 天气风险提示</span><span>○ 酒店实时查询即将接入</span></aside></section><section className="panel"><div className="section-head"><div><span className="eyebrow">01 / 旅行需求</span><h2>开始规划</h2></div><small>信息仅用于本次规划</small></div><form onSubmit={submit}><div className="grid"><label>目的地<input required name="destination" placeholder="如：杭州" defaultValue="杭州" /></label><label>出发日期<input required type="date" name="startDate" defaultValue={today} /></label><label>旅行天数<input required type="number" name="days" min="1" max="10" defaultValue="2" /></label><label>总预算（元）<input required type="number" name="budget" min="500" defaultValue="4000" /></label><label>出行人数<input required type="number" name="travelers" min="1" max="8" defaultValue="2" /></label><label>主要交通<select name="transport"><option value="walk">步行优先</option><option value="transit">公共交通</option><option value="drive">驾车/打车</option></select></label></div><label>旅行偏好<textarea name="preferences" placeholder="如：西湖、茶文化、本地美食、慢节奏" /></label><label>限制与禁忌<textarea name="constraints" placeholder="如：不吃牛肉、避免高强度徒步、不安排夜间行程" /></label><button disabled={loading}>{loading ? '正在校验路线…' : '生成可信旅行方案  →'}</button></form>{error && <p className="error">{error}</p>}</section>{plan && <PlanView plan={plan} />}</main>;
}
function PlanView({ plan }: { plan: Plan }) { const total = Object.values(plan.budget).reduce((a,b) => a+b, 0); const budgetLabels: Record<string, string> = { transport:'交通',stay:'住宿',food:'餐饮',activities:'体验',buffer:'机动金' }; return <section className="result"><div className="section-head"><div><span className="eyebrow">02 / 旅行方案</span><h2>{plan.request.destination} · {plan.request.days} 天行程</h2></div><small>更新于 {new Date(plan.sources.updatedAt).toLocaleString('zh-CN')}</small></div><div className="notice">当前数据状态：AI {sourceName(plan.sources.ai)} · 地图 {sourceName(plan.sources.map)} · 天气 {sourceName(plan.sources.weather)} · 酒店 {sourceName(plan.sources.hotel)}。演示数据不代表实时地点或价格。</div><div className="layout"><div>{plan.days.map(day => <article className="day" key={day.date}><h3>{day.title}<small>{day.date}</small></h3>{day.stops.map((stop, i) => <div className="stop" key={`${day.date}-${stop.id}`}><time>{stop.time}</time><div><strong>{stop.name} {stop.verified && <i>已校验</i>}</strong><p className="address">⌖ {stop.address}</p><p>{stop.detail}</p><div className="tags"><span>停留 {stop.duration}</span><span>{stop.indoor ? '室内/可避雨' : '户外活动'}</span>{i > 0 && <span>按距离优化排序</span>}</div></div><b>约 ¥{stop.cost}</b></div>)}</article>)}</div><aside className="sidebar"><div className="card weather"><span className="eyebrow">天气建议 · {sourceName(plan.weather.state)}</span><h3>{plan.weather.summary}</h3><b>{plan.weather.low}° — {plan.weather.high}°</b><p>降水概率 {plan.weather.rain}% · 数据更新于 {new Date(plan.weather.updatedAt).toLocaleTimeString('zh-CN')}</p></div><div className="card"><span className="eyebrow">预算估算</span>{Object.entries(plan.budget).map(([key, value]) => <p className="line" key={key}><span>{budgetLabels[key]}</span><b>¥{value}</b></p>)}<p className="line total"><span>合计</span><b>¥{total}</b></p></div><div className="card"><span className="eyebrow">住宿推荐 · 待接入</span><h3>{plan.hotels[0].area}</h3><p>接入酒店供应商后，将按行程重心、日期、人数与预算返回实时房价与预订跳转。</p></div><div className="card"><span className="eyebrow">出行提醒</span><ul>{plan.risks.map(r => <li key={r}>{r}</li>)}</ul></div></aside></div></section>; }
